#!/usr/bin/env bash
#
# One-line "publish a submission CSV" helper. Stages, commits, and pushes
# a single file under submissions/ so the GitHub repo always has the
# latest CSVs ready to download from any machine.
#
# Usage:
#     scripts/push_submission.sh <csv_path>
#     scripts/push_submission.sh submissions/sc_phase0_k8_private.csv
#     scripts/push_submission.sh submissions/sc_runb_k8_private.csv "Run B + K=8 SC"
#
# Optional second arg = a short description that goes into the commit
# message body. Defaults to file size and row count.

set -euo pipefail

cd "$(dirname "$0")/.."

if [ $# -lt 1 ]; then
    echo "Usage: $0 <submissions/foo.csv> [description]"
    exit 1
fi

CSV="$1"
DESC="${2:-}"

if [ ! -f "$CSV" ]; then
    echo "ERROR: $CSV not found"
    exit 1
fi

# Sanity-check it really IS a submission CSV.
case "$CSV" in
    submissions/*.csv) ;;
    *) echo "ERROR: $CSV must live under submissions/"; exit 1 ;;
esac

# Verify schema before publishing — catches the case where we'd push a
# half-baked CSV (missing rows, no header, no boxed answers).
SUMMARY=$(python3 - <<PY
import csv
import sys

with open("$CSV") as f:
    rows = list(csv.DictReader(f))
if "id" not in rows[0] or "response" not in rows[0]:
    print("ERROR: missing id or response column", file=sys.stderr)
    sys.exit(1)

n = len(rows)
ids = {int(r["id"]) for r in rows}
boxed = sum(1 for r in rows if "\\\\boxed{" in r["response"])
size_mb = round(__import__("os").path.getsize("$CSV") / 1024 / 1024, 1)

print(f"rows={n}  unique_ids={len(ids)}  boxed={boxed} ({100*boxed/n:.1f}%)  size={size_mb}MB")
PY
)
echo "Validating: $SUMMARY"

git add "$CSV"

# Bail out gracefully if there's nothing to commit (e.g., re-running with
# the same identical CSV).
if git diff --staged --quiet; then
    echo "Nothing to commit — $CSV is already at the latest committed version."
    exit 0
fi

git commit -m "$(cat <<EOF
Publish $(basename "$CSV")

$SUMMARY

${DESC:+$DESC

}Generated by scripts/run_sc_*.sh on this branch.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>
EOF
)"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
git push origin "$BRANCH"

cat <<EOF

✓ Pushed $CSV → origin/$BRANCH

To download from another machine:
    git fetch && git checkout origin/$BRANCH -- $CSV
or:
    curl -L -o $(basename "$CSV") \\
        "https://raw.githubusercontent.com/QingyuanYuu/cse151b-sp26-comp/$BRANCH/$CSV"
EOF
